### ISSUE TITLE
DualSenseX App issue

### ISSUE THREAD

**Issue by feiercrack** [ViGEm/HidHide#101]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
----------------------------------------

### Bug description
HidHide does not work with DualSenseX 1.4.9 App / PSRemote 5.5.0.08250

### Steps to reproduce
start psremote.exe
play virtual
try to make e.g. windows update
virtual gamepad / controller jumps over ghostly to different links in the tab

sholud i try the DS4Windows / Driver App instead of DualsenseX with my PS5 Controllers? 

### Machine info
<!-- Asus A17 Laptop->
**CPU-Architecture:** AMD Ryzen 7 6800H

**Windows version:** Windows 11 Home 22H2 x64
**Software/driver version(s):** 1.2.98.0

**Comment by nefarius** [comment]
HidHide doesn't have any influence over the controller content and behaviour, it either hides them or not.
