### ISSUE TITLE
Refuses to install without internet connection

### ISSUE THREAD

**Issue by i010011010** [ViGEm/HidHide#102]
There's no possible reason for this to require internet to function or install.  The installer should have exactly what is needed to install it without needing to talk online.

![hidhide](https://user-images.githubusercontent.com/1456603/221014481-0703baa8-2771-403f-98ab-a0e2d8cf066b.png)

**Comment by nefarius** [comment]
Yes there is. The installer checks if required VC++ redistributables are installed and fetches them online if not. Including them would just needlessly blow up the size of the setup in this day and age of Internet availability. You're welcome to submit a PR to make the setup more resilient. It's a third party product so there's only so much I can do about. My current time budget doesn't allow me to look into this bit I'll happily accept a quality PR. Until then fix your Internet connectivity and everything will be fine.

Cheers

**Comment by i010011010** [comment]
You're missing the point.  The problem isn't my internet, it's your software trying to talk online when it has absolutely no business.  In this day and age of internet availability, I can download and install vc++ redistributables on my own.  Please remove the flag that mandates internet connectivity as it is not needed.
