### ISSUE TITLE
Wrong whitelist checks due to Kaspersky Security Cloud

### ISSUE THREAD

**Issue by jdubus** [ViGEm/HidHide#14]
I'm using Kaspersky Security Cloud as an anti-virus software, but due to that, all whitelisted programs (in my case Joystick Gremlin) in HidHide somehow get redirected to `\Device\HarddiskVolume4\Program Files (x86)\Common Files\Kaspersky Lab\klhk\klhk_x64\klhkum.dll` during whitelist checks.

Meaning that the whitelist is completly non functional as the path never match.

The only time the whitelist actually work is if i deactivate Kaspersky, clear the whitelist and redo it and then launch any of the whitelisted applications while Kaspersky remain deactivated. Those applications are then properly recognized as whitelisted, but then if i reactivate Kaspersky they all once again get redirected permanently to the above dll no matter the actual state of Kaspersky until i once again deactivate Kaspersky and redo the whitelist.

Since i can't really play while keeping the anti-virus deactivated for lengthy periods of time i'm unable to make proper use of HidHide.

**Comment by nefarius** [comment]
Sounds like a case for the Kaspersky support to me 😁 AV ruins it? AV has to fix it 😜

**Comment by triscan** [comment]
quick fix:
Turn off Kaspersky Self-Defense and rename klhkum.dll to whateveryouwant.
Turn on Kaspersky Self-Defense and reboot.

**Comment by nefarius** [comment]
Closed as nothing came of it.
