### ISSUE TITLE
The name of a hidden device will change after refreshing the HidHide device list.

### ISSUE THREAD

**Issue by Serfrost** [ViGEm/HidHide#16]
Using HidHide to hide my DualSense after allowing DS4Windows through so it's set as an Xbox 360 emulated controller. (To prevent double controller connections on games, as expected.) However, it changes the name to _HID-compliant Game Controller_ after reopening the app or swapping in-app tabs.

This isn't a big deal if you only have one controller connected like myself, but this could become a mess if you have two or more in use at the same time. I'd like to see it save the original name and use that at all times for that device.

PS: Noting if a controller is connected via cable or bluetooth may help as well, if you have multiple controllers of the same type connected in different ways.

Before:
![image](https://user-images.githubusercontent.com/19275542/116082177-ba717100-a660-11eb-9f8e-281fefb73068.png)

After:
![image](https://user-images.githubusercontent.com/19275542/116081758-41721980-a660-11eb-931d-f3cae2bfed8b.png)

**Comment by nefarius** [comment]
You need to whitelist the config UI as well so it can query the device manufacturer name and product name again 😉 we added auto-self-whitelisting to the upcoming release to make this process automated.

**Comment by Serfrost** [comment]
> You need to whitelist the config UI as well so it can query the device manufacturer name and product name again 😉 we added auto-self-whitelisting to the upcoming release to make this process automated.

Oh, derp.  I just read that issue, too.  I didn't even think about this. lmao

Thanks for the quick response.  Looking forward to this app's support.  So simple and easy to use compared to HidGuardian.

**Comment by nefarius** [comment]
> Thanks for the quick response. Looking forward to this app's support. So simple and easy to use compared to HidGuardian.

Thanks for the feedback. A complete rewrite and redesign was the right choice 😅

**Comment by tnt-debug** [comment]
Hi,

I added all these HID and send with IOCTL_SET_BLACKLIST, but nothing change...

The paths yes, are added correctly to applications, maybe I don't have the correct HID? it's a DualShock V2.

   @"HID\VID_054C&PID_09CC&MI_03",
                @"HID\VID_054C&PID_05C4",
                @"HID\VID_054C&PID_09CC&MI_03",
                @"HID\VID_054C&PID_0BA0&MI_03",
                @"HID\VID_054C&PID_09CC&REV_0100&MI_03",
                @"HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4",
                @"HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc",
                @"HID\VID_045E&PID_028E&IG_00\3&8968588&0&0000",
                @"HID\VID_054c&PID_09CC&MI_03\8&1657DD3C&0&0000",
                @"USB\VID_054C&PID_09CC\6&1F6504EA&0&6"

![image](https://user-images.githubusercontent.com/32776076/117809991-21954500-b25f-11eb-8a1d-4fd239a1b91b.png)

Thanks in advance.
