### ISSUE TITLE
Help with API usage (blacklisting)

### ISSUE THREAD

**Issue by nefarius** [ViGEm/HidHide#20]
Hi,

I added all these HID and send with IOCTL_SET_BLACKLIST, but nothing change...

The paths yes, are added correctly to applications, maybe I don't have the correct HID? it's a DualShock V2.

   @"HID\VID_054C&PID_09CC&MI_03",
                @"HID\VID_054C&PID_05C4",
                @"HID\VID_054C&PID_09CC&MI_03",
                @"HID\VID_054C&PID_0BA0&MI_03",
                @"HID\VID_054C&PID_09CC&REV_0100&MI_03",
                @"HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4",
                @"HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc",
                @"HID\VID_045E&PID_028E&IG_00\3&8968588&0&0000",
                @"HID\VID_054c&PID_09CC&MI_03\8&1657DD3C&0&0000",
                @"USB\VID_054C&PID_09CC\6&1F6504EA&0&6"

![image](https://user-images.githubusercontent.com/32776076/117809991-21954500-b25f-11eb-8a1d-4fd239a1b91b.png)

EDIT1: 

I want to remove "Wireless Controller".

Thanks in advance.

_Originally posted by @tnt-debug in https://github.com/ViGEm/HidHide/issues/16#issuecomment-838333689_

**Comment by tnt-debug** [comment]
Seems now is OK, thanks!
