### ISSUE TITLE
HidHide starts, but does nothing

### ISSUE THREAD

**Issue by machomuchacho** [ViGEm/HidHide#22]
The first time I tried it, it worked, but now it just won't, even though I have disabled my antivirus, and I have no idea why :( ... prerequesites are installed

**Comment by Kanuan** [comment]
you are providing no useful info that can be used to help you.
Have you followed [HidHide's guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/)?

**Comment by machomuchacho** [comment]
I know, the thing is that I really don't know what it could be, and yes I did follow the guide

**Comment by Kanuan** [comment]
Send a screenshot of HidHide configuration client `Applications` tab

**Comment by machomuchacho** [comment]
![Capture2](https://user-images.githubusercontent.com/56357709/120187359-f924b900-c214-11eb-859c-93fba54dc440.PNG)
I have set only UCR to see through the cloak, but Steam also detects it, and when I press the middle button of my controller (the home button) the Xbox game bar and menu shows up

**Comment by machomuchacho** [comment]
Here's what I tried :
-Following the [guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/)
-Repairing and completely reinstalling HidHide and prerequesites and then rebooting
-Whitelisting HidHide in Windows Defender (no other antivirus on my PC) and doing all over again lol

**Comment by Kanuan** [comment]
If I recall correctly, HidHide can't hide controllers from some Windows functions. I just tested, and even with the (virtual) Xbox 360 controller hidden windows can still detect the Home button press, so this function needs to be disabled in Windows' settings -> Gaming to prevent this.

![image](https://user-images.githubusercontent.com/24910442/120188216-388adf80-c1ec-11eb-8e35-537933461e86.png)

Regarding Steam, maybe you just need to restart it? After Steam picks the controller it will keep detecting it even if you hide the controller after. You need to fully restart Steam (After closing it, open Windows' Task manager and check if there is some Steam related process still running to confirm) or re-plug the controller. In case of UCR, stop and starting the profile again should do the trick.

If that doesn't work, maybe you have enabled Steam custom XInput driver and it is picking the controller in a level before HidHide. Try disabling `Xbox Extended feature support` if it is enabled.

![image](https://user-images.githubusercontent.com/24910442/120188550-a59e7500-c1ec-11eb-8e5b-fc4be18b65aa.png)

**Comment by machomuchacho** [comment]
It's a Nacon Compact Controller for PS4, so I think it's DirectInput since it's not an official Xbox controller, and the first time I tried it, it was on Steam and it just worked...
I also tried hiding the device *before* starting Steam.

**Comment by Kanuan** [comment]
Send a screenshot of Steam's detected controllers screen, like on my screenshot

**Comment by machomuchacho** [comment]
![image](https://user-images.githubusercontent.com/56357709/120190661-31c69180-c219-11eb-8e09-5b37b28b9e30.png)
Hold on I don't think it was written "Xbox One controller" before 💀 though I'm not sure. I don't even have an Xbox One controller profile on UCR ^^'

**Comment by Kanuan** [comment]
This is probably the virtual controller UCR creates. I'm using a virtual Xbox 360 controller and Steam also recognizes it as a Xbox One controller too. Everything seems to be working as it should
