### ISSUE TITLE
Signal for active device

### ISSUE THREAD

**Issue by roozye** [ViGEm/HidHide#23]
In devices tab, there is a lot of same-named devices, it's hard to distinguish which device need to checked and get invisible.
It's good to have a feature that Highlights the device which Interacted/Button-Pressed and then user knows that device is the thing!

**Comment by nefarius** [comment]
This is out of scope, the way the current client is designed would basically require a partial rewrite and not worth it.

If someone wants to build a companion solution with this feature, be my guest.
