### ISSUE TITLE
HidHide Client is targetting the wrong harddiskvolume

### ISSUE THREAD

**Issue by ferrazpedro** [ViGEm/HidHide#24]
When I try to add any executable in my C:\ drive with the client, it mistakes the correct volume. Here is an example:

![image](https://user-images.githubusercontent.com/37643357/120690935-33dc5a80-c47c-11eb-8ae6-89dfb9cfa087.png)

DS4Windows automatically adds itself to the list, so the correct volume appears to it. Every other .exe I add targets the wrong volume.

**Comment by nefarius** [comment]
Duplicate of #9
