### ISSUE TITLE
Add filter option for virtual devices

### ISSUE THREAD

**Issue by Kanuan** [ViGEm/HidHide#25]
Because in most situations the user wants to hide only physical controllers, it would be good to have a filtering option that hides virtual controllers, making the usage more intuitive, though I guess that would only work if HidHide knows what to look for? (vigemBUS spawned controllers for example)

**Comment by nefarius** [comment]
Note: that's a **client** topic, not a driver topic. The driver theoretically also can look-up the device parents but that gets messy really quickly and should be avoided and kept done in user-land. Also, the next release with the scripting/CLI interface might deprecate this need anyway.

**Comment by nefarius** [comment]
There is no reliable way for this as you'd need to address every virtual controller solution out there in the client UI logic (and there are quite a few, not only ViGEmBus) so I consider this out of scope.
