### ISSUE TITLE
HidHide device list is language-aware

### ISSUE THREAD

**Issue by Serj-Lewa** [ViGEm/HidHide#3]
Hello! Hidhide show me these devices:
![image](https://user-images.githubusercontent.com/60753220/113475687-d4fc6400-947f-11eb-9a7a-2bcd61f521a8.png)

It's using my Windows language and weird names like: "HID-compatible system controller" or "HID-compliant wireless radio controls".

Would like to see something like Virtual Controller provides as a hid device list:
![image](https://user-images.githubusercontent.com/60753220/113475919-b9de2400-9480-11eb-8264-83a702859b11.png)

**Comment by nefarius** [comment]
The names you see there are taken directly from the API Windows provides to get manufacturer and product name. Some devices support "localised" names which is probably what happens here.

Not sure if bug or feature 😁

**Comment by nefarius** [comment]
Btw. you also need to add the client UI itself to the allowed applications list or it will get blocked too, that's why you see the generic name 😉

**Comment by Kanuan** [comment]
Feature request: have the client white-list itself without the needing of its entry appearing on the list. No reason for this to not be the default behaviour, right?

**Comment by nefarius** [comment]
Closed due to being unfixable with the current use of the WinAPI.
