### ISSUE TITLE
Devices Tab in Config Client Stops Responding

### ISSUE THREAD

**Issue by Kenpari** [ViGEm/HidHide#33]
I installed HidHide with no issues and hid the controllers I wished to when I first started up the configuration client. However, any subsequent time I try to navigate into the Devices tab on the config client, the client freezes and windows says it's stopped responding. I've noticed that a few times it will actually load after several minutes, but many times it simply seems to not work at all. 

Additionally, though the Applications tab loads fine when starting the config client, it will freeze when trying to navigate back to it if the Devices tab does indeed load after a couple minutes of not responding. Tried uninstalling/reinstalling the client to no avail.

**Comment by nefarius** [comment]
Can't reproduce, no further details received.

**Comment by TheFreezingChicken** [comment]
I have the same issue, and in my case it seems related to my Corsair K95 Keyboard.
The behavior is exactly as described by @Kenpari, but I found out that if I disconnect and reconnect my keyboard it goes away (a quicker way is also to change the position of the polling rate switch behind the keyboard, which causes a re-connection).
I have no idea what causes this on a hardware or software level, but it would be interesting to know if everyone who's experiencing this issue has the same device or a similar device (like for example another keyboard with high polling rate).

(P.S.: I hate Corsair -.-)

**Comment by nefarius** [comment]
Corsair should be banned from manufacturing HID devices, 2 mice and one mechanical keyboard I got from them broke within 1 or 2 years, absolute trash. Back to Logitech, quality.

**Comment by TheFreezingChicken** [comment]
I'll fix your sentence. "Corsair should be banned from manufacturing". Period 😂 
I had many Corsair items. Headphones, mouse, keyboard, water cooling, a case... and they all had either some easily fixable design flaws or very fast degrading quality or technical issues.

The only good thing about them is the customer support, which makes you wonder why they need excellent customer support in the first place 🙄

**Comment by Patz12** [comment]
OMG... I can't believe that this issue was related to the same exact model of keyboard, I hope that my Logitech mice doesn't also cause the same problem...
My keyboard RGB LEDs died months after purchase, and I was considering another keyboard, with this thing I definitely need to find another one

**Comment by hb0nes** [comment]
I have a K70 actually, and have the same problem. Flicking the polling switch worked.

# Off-topic
````
BTW to all the Corsair haters here, I have had mechanical Corsair keyboards for many, many years without any problems.
As well as highly rated PSU's, iCUE H150i Elite Capellix, QL120 fans.
Not. A. Single. Problem.

**Comment by TheFreezingChicken** [comment]
Sad thing is... I've recently reinstalled Windows and everything, and now for some reason the polling switch trick doesn't work anymore 😢 (same keyboard, same OS, same configs...)

**Comment by Patz12** [comment]
> Sad thing is... I've recently reinstalled Windows and everything, and now for some reason the polling switch trick doesn't work anymore 😢 (same keyboard, same OS, same configs...)

Try to disconnect your keyboard before using HidHide, I try it today and it worked, just open the window before or use the virtual keyboard to find HidHide

**Comment by ttenor12** [comment]
Issue still going on as of February 2023. I use a Corsair keyboard but it happens even if it's disconnected.

**Comment by LorkHang** [comment]
I had the same issue with K65RGB, reverting to a old firmware (v2.05) seems to have fixed it.

Here's the instruction on how to manually install a firmware bin file:
IMPORTANT NOTE: Backup your current firmware from your keyboard first before REPLACING it !!
https://imgur.com/a/d41z5Gu

I am able to acquire the old firmware for my K65 by using CUE version 2.24 and click the update button.
You can find the installer for CUE 2.24 here: https://forum.corsair.com/forums/topic/111865-have-issues-unofficial-faq-and-quick-fix-guide/
Alternately, I have the old copy of it that do not need to install to run it:
https://drive.google.com/file/d/1K8wEUQLYCL5QsyiBp49qLSzmA-wCtWlI/view?usp=sharing

If you have the same KB as mine, which is K65 RGB. Here's the v2.05 firmware bin file for it:
https://drive.google.com/file/d/1OJpSM4M2yOTsYj39DrZ-lvJwhy5_BQzi/view?usp=sharing

Besk luck to you all.

**Comment by Watch251** [comment]
Hi, Hidhide freezes when going to the device tab. I don't have corsair products. It takes 5-10min for the app to go from "Not responding" to work again. Got an update today and had to reinstall ds4 because It broke after forcing a restart. This is unacceptable on a high end pc. There is definitely something wrong with the app.

My specs: i9-12900k
3080 ti
32gb 3600 cl16

**Comment by Patz12** [comment]
> Hi, Hidhide freezes when going to the device tab. I don't have corsair products. It takes 5-10min for the app to go from "Not responding" to work again. Got an update today and had to reinstall ds4 because It broke after forcing a restart. This is unacceptable on a high end pc. There is definitely something wrong with the app.
> 
> My specs: i9-12900k 3080 ti 32gb 3600 cl16

Check if one of your devices causes the issue, thats how I discovered that my Corsair K95 RGB hated HidHide.
I recently bought a new one from the same brand (K70 TKL) and I dont need to unplug it like my old keyboard.
Hopefully that helps, maybe firmware, software and bios updates could also help.

**Comment by BigheadSMZ** [comment]
This is still a problem as far as I know. Friend of mine has a corsair keyboard and hidhide causes all kinds of issues with his system. When opening hidhide the program will completely lock up. So I told him about the solution found here, unplug the keyboard hide the controller, close hidhide, and then replug the keyboard. At random he said his entire computer would start acting funny, at random everything would start lagging/hanging, similar to the lag that happens with a dying hard drive or some other storage medium. He eventually just uninstalled hidhide which is a shame. I suppose the only solution is for him to buy a new keyboard. I have no problems with mine though its not by corsair.

**Comment by nefarius** [comment]
Sucks but without anybody properly investigating and submitting a solution; it is what it is.

**Comment by Ares9323** [comment]
Isn't there a way to ignore corsair devices? I have both a K95 and a Corsair Scimitar (Mouse) and they both cause the same issue, I have to unpug both in order to unfreezet HidHide

**Comment by BlueStarBRS** [comment]
> Can't reproduce, no further details received.

on my pc i need to replug my headset i can confirm this bug exist and its rly anyoing

**Comment by nefarius** [comment]
> > Can't reproduce, no further details received.
> 
> on my pc i need to replug my headset i can confirm this bug exist and its rly anyoing but my headset is a sharkoon skiller sgh2 and not a corsair device

We don't need confirmation, we need someone to step in and contribute a fix. Until then it is what it is.

**Comment by Patz12** [comment]
Just an update over here:
LOL I ended buying another Corsair keyboard, this time was a K70 TKL. HidHide is working properly, my theory now is, this might be caused by older Corsair devices such as my old K95 with 18 M-keys.
The same trick still applies, where you either flip the polling rate switch or physically disconnect your device.

**Comment by Dantasstic** [comment]
> this time was a K70 TKL. HidHide is working properly, my theory now is, this might be caused by older Corsair devices such as my old K95 with 18 M-keys

I have the issue and have a K70 LUX

**Comment by BigheadSMZ** [comment]
Would it be possible to maybe have an option to ignore specific devices set by the user? I was thinking of something like an "ignore list" where a user could enter the title or guid of any devices they want to ignore, and HidHide will not even try to access them, which could in theory prevent it from hanging. For example, my Wii remote, enter either the title "**Nintendo RVL-CNT-01**" or the guid "**e0cbf06c-cd8b-4647-bb8a-263b43f0f974**" and HidHide will ignore it completely. Apologies if this is a bad idea or isn't possible. I have no idea how feasible this is as I have zero knowledge on the inner workings of human interface devices or how HidHide works.

**Comment by rogersmj** [comment]
I found my way here, having the same problems as OP and I also have a Corsair keyboard. Haven't been able to make it work with the firmware workaround mentioned above.

> Would it be possible to maybe have an option to ignore specific devices set by the user? I was thinking of something like an "ignore list" where a user could enter the title or guid of any devices they want to ignore, and HidHide will not even try to access them, 

I think this would probably be a good idea.
