### ISSUE TITLE
v1.1.50 CLI not fully working

### ISSUE THREAD

**Issue by vrs99-hub** [ViGEm/HidHide#45]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using the command line interface to temporarily hide 6 USB controllers.

The changes are reflected in the HidHide Configuration Client interface afterwards but not in (for example) the Windows gamepad control panel. So the changes aren't fully enacted.

But, when I change the status of any controller in the HidHide Configuration Client after the steps above, then all changes made through the CLI do also show up in the gamepad control panel.

Changes made directly through the HidHide Configuration Client work perfectly fine. And Windows/the gamepad control panel are not allowed through the cloack

### Screenshots

![HidHideCLI-Issue](https://user-images.githubusercontent.com/90147299/132133715-fd9f0729-e815-421c-83d5-5e052656ccde.png)

### Machine info

- x64,
- Windows version:** Windows 10 20H2
- Software/driver version(s):** 1.1.50

**Comment by nefarius** [comment]
Careful! Hiding the **USB** instance **only works for XInput devices!** For your general purpose joystick, pad, wheel etc. you need to block the **HID-Instance**, e.g. `HID\VID_054C&PID_0268`

Cheers

**Comment by vrs99-hub** [comment]
Thank you for the clarification. Using the HID-Instance it works like a charm!
