### ISSUE TITLE
Hiding of PS5 Controller not working after Windows 10 21H1 Update

### ISSUE THREAD

**Issue by flok** [ViGEm/HidHide#48]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------
Thanks for this tool. Really working great in use with DS4Windows!

### Bug description
After updating to Windows 10 21H1 it seems like i cant hide the original PS5 Controller anymore. DS4Windows shows the device with HidHide exclusive access. setting were not changed inside DS4Windows. Tried rehiding the device and multiple restart but can't get it to work.

### Steps to reproduce
Didnt to anything except update to 21H1 With Build 1904.1237

**Actual result:** Device is still shown inside game (Trackmania) and joy.cpl also shows the device even if its hidden in the configurator.
**Expected result:** Hiding of the PS5 Controller.

### Screenshots
![image](https://user-images.githubusercontent.com/37000563/135506697-e7740f16-61f4-44e0-b43b-7be1d9315d21.png)

### Machine info

**CPU-Architecture:** x64,
**Windows version:** Windows 10 21H1 (Build 1904.1237)
**Software/driver version(s):** 1.1.50.0

### Any other helpful information

Is this maybe also related to #39  ?

**Comment by ferrazpedro** [comment]
@flok hey! How have you resolved this issue?

**Comment by ferrazpedro** [comment]
Just found what my problem was, if anyone else stumbles upon this:

![image](https://user-images.githubusercontent.com/37643357/141125524-801f3cdc-ccdb-48bf-9539-0e6b5ca69631.png)

This checkbox wasn't marked! Just mark it again and everything will work just fine :D
