### ISSUE TITLE
Does not work for multiple Windows user accounts

### ISSUE THREAD

**Issue by hensez** [ViGEm/HidHide#56]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
HidHide is unable to function in a situation where two people use the software on different user accounts.

### Steps to reproduce
- Install HidHide for User 1
- User 2 is unable to launch the configuration utility
- Reinstall for User 2
- Installation is now broken for User 1

**Actual result:** Only one user is able to use HidHide on one PC.
**Expected result:** Both users are able to use HidHide.

### Machine info

**CPU-Architecture:** x86-64
**Windows version:** Windows 11 21H2
**Software/driver version(s):** 1.1.50

**Comment by nefarius** [comment]
There are still people with multiple user accounts? 😄 Jokes aside, what exactly is "broken"? The config client not launching? Blocking and whitelisting not working anymore? Bit more info please 😘

**Comment by hensez** [comment]
I'm probably the only one, yeah. Yes, the config client does not start up. Says to check device manager for driver status, which seems to be ok (no yellow triangle or anything). Blocking and whitelisting are not working.

**Comment by nefarius** [comment]
Screenshot? Is it open on the other user account in parallel? Because only one instance on the whole machine is allowed to run simultaneously. That is intentional and can't be changed. Black and whitelisting are system-wide operations so that doesn't sound right being tied to user account.

**Comment by Kanuan** [comment]
Does the client opens if explicitly run as admin on the other account? On my test I also couldn't open the HidHide Client from the 2nd user in the usual way (crashed when opening with a error message saying something went wrong), but it opens as normal if using the "run as administrator" option.

**Comment by hensez** [comment]
Interesting. After a complete reinstall it now works perfectly. I wonder what went wrong with the earlier reinstalls. I guess Windows needed a day to cool off.

**Comment by nefarius** [comment]
We still try to get to the bottom of this, the client app is a portable executable not tied to anything in the user profile so only thing I can think of is some incorrect file and folder permissions set by the setup on the install directory 🤔

**Comment by nefarius** [comment]
Can't reproduce.
