### ISSUE TITLE
Feature Request: Per game/app configuration

### ISSUE THREAD

**Issue by NoSie** [ViGEm/HidHide#6]
Great stuff!
My games (mostlys flight sims) are usually limited in the # of game device and I use different devices for different games.
So a per game config would be great to hide different devices for different games automatically.

**Comment by Kanuan** [comment]
HidHide does exactly 2 things: hide controllers /allow aplications. What you need is _another_ program that _manages_ HidHide by using its API (a program that checks what app you are using and then sets HidHide configurations accordingly)

**Comment by NoSie** [comment]
Ah, thanks for the hint! I'll have a look into the API!

**Comment by nefarius** [comment]
[Here's the link btw.](https://vigem.org/projects/HidHide/API-Documentation/) 😉

**Comment by nefarius** [comment]
This can now be achieved with the shipped command line client, which supports importing and exporting your configuration.
