### ISSUE TITLE
HidHide broken on latest windows insider update

### ISSUE THREAD

**Issue by TheNintendoReject** [ViGEm/HidHide#68]
### Bug description
HidHide has stopped working properly with the latest windows insider build. 

### Steps to reproduce
- Update windows 11 to Insider build 22579.1
- Open DS4Windows with HidHide running. (The lock icon displays on DS4Windows under EX, suggesting that it's functioning)
- Open game

**Actual result:**  Controller inputs are not being recognized with desired game (Specifically, Honkai Impact 3)
**Expected result:** Controller works as intended with desired game 

![image](https://user-images.githubusercontent.com/23401536/159208575-1128118a-a7ce-45af-8ec5-d2c7b61d22b7.png)

Edition         Windows 11 Pro
Version         22H2
Installed on    3/20/2022
OS build        22579.1
Experience      Windows Feature Experience Pack 1000.22579.1.0

**Comment by TheNintendoReject** [comment]
Alright, so it seems that re-installing the driver worked... but the fact that it broke after a **specific** windows update is still confusing to me

**Comment by nefarius** [comment]
Windows 11 is a joke, change my mind 😏

**Comment by TheNintendoReject** [comment]
Ok, might wanna re-open this. The newest windows insider is *actually* broken now for hidhide.
