### ISSUE TITLE
Version 1.2.93 labelled as version 1.2.87.0

### ISSUE THREAD

**Issue by xcasxcursex** [ViGEm/HidHide#74]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App is still labelled with the same version as previous to the update (which otherwise worked very smoothly, nice)

### Steps to reproduce
- have hidhide installed? (I did, Possibly not necessary)
- update (or maybe install from scratch?)
- be confused whether it is the right version or not
- (optional) update again, uninstall, reinstall. Same.

**Actual result:** Version is not the new one
**Expected result:** Version is the new one

### Screenshots
Note: Control Panel says new version, UI says old, file properties says old.
![image](https://user-images.githubusercontent.com/58130821/175966559-522fde53-ea32-4ff2-a15a-e231eda376c3.png)

### Machine info

**CPU-Architecture:** x86
**Windows version:** Windows 10 20H2
**Software/driver version(s):** Heh, good one.

### Any other helpful information

I was trying the test build for inverting the list. The first night, it auto-updated to the same version, obviously not intentional, and I thought, I'll see if it loops or not before I report this (as in, is it doing it every time it checks or did it just do it once). It didn't, it just went the once, but it may be relevant now so I mention it. Today it updated and it really was an update, but...sorta?

**Comment by nefarius** [comment]
That's normal, the binaries have not changed between the releases and I don't resubmit everything for signing if nothing has changed, it's just overhead. Next release will most probably be in sync again.
