### ISSUE TITLE
Multiple feature requests/suggestions regarding client UI

### ISSUE THREAD

**Issue by AAide** [ViGEm/HidHide#8]
1 It would be good to add the drag and drop of files to add them to the list.

2 Added the possibility of assigning a keyboard shortcut to activate or deactivate the device of our choice, or if it is easier to deactivate hidhide with a shortcut and re-use the same shortcut to reactivate hidhide.

3 Added the ability to start with windows in the notification area.

4 Added the possibility of deactivating hidhide by clicking on the hidhide icon in the notification area and when you click on it again it activates. And if you want to access the interface again added the possibility to right click on the icon and choose open or parameter or something like that.

5 Add the possibility to export the whitelist.

6 Add the possibility to choose if you want to enable hide a device for an element that has been added to the whitelist, because there are games that detect the controller when 'enable hide device' is checked and other games which does not need that 'enable hide device' to be checked for it to work, otherwise it will become a problem and must each time manually activate this checkbox, so the best is to create a profile for each element of the list which chooses which device element to be checked, but for the moment there is only 'enable hid device' which poses a problem for some games.

7 Add update search and a notification to say there is a new update

I think these are interesting things

**Comment by nefarius** [comment]
1. Got implemented in an upcoming release

**Comment by AAide** [comment]
Thanks, I'll keep you posted on my experience with this upcoming release and tell you what I think.

**Comment by nefarius** [comment]
## Update with v1.1.50

1) is implemented
2) won't be implemented, but you can use the new command line client to customize all settings the UI offers
3) won't be implemented
4) won't be implemented, but you can use the new command line client to customize all settings the UI offers
5) can be achieved by included command line client
6) I don't really understand this remark
7) out of scope, investing into an updater is an underestimated challenge and not worth it with the current release frequency and available developer resources

**Comment by AAide** [comment]
Thanks for this release, dragging and dropping exe files is really good.

But how do I go about using the commands? And where do I find the list of commands?
