### ISSUE TITLE
Unable to Install - No Internet Connection

### ISSUE THREAD

**Issue by Erokaution** [ViGEm/HidHide#82]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic
- [x] I have read https://vigem.org/Community-Support/

----------------------------------------

### Bug description
When running the installer, a error pops up saying;
"HidHide requires an active internet connection for installation. Please check your network configuration and proxy settings".
I should note, I do in fact have a usable and stable internet connection through a cable. 
Under Network Connections on Windows 10, I have a bluetooth network that isn't connected, a Ethernet connection that is connected, and a VirturalBox host-only network that is enabled but not being used.
I've also attempted to run the installer as admin, and go the same result.

### Steps to reproduce
- Download installer
- Open installer
- That's it.
Due to the nature of the bug, I have no idea how to actually diagnose why this is happening or give any better steps to reproduce.

**Actual result:** Can't use the installer due to it not seeing my internet connection.
**Expected result:** Being able to install the program.

### Screenshots
![image](https://user-images.githubusercontent.com/24382126/185832765-727fca2f-dea2-4e79-96ce-910f62527449.png)

### Machine info
**CPU-Architecture:** x64
**Windows version:** Windows 10 20H2
**Software/driver version(s):** 1.2.98

**Comment by LyohaPro** [comment]
The problem may be due to DNS settings. For example, I'm using Simple DNSCrypt and I had to disable it in order to start the installation.
In any case, this is not a normal situation. Let then the installers in the future immediately contain everything you need.

**Comment by nefarius** [comment]
The installer does contain everything necessary, it needs Internet access to check for prerequisites, which I will not bundle because it will just artificially and unnecessarily inflate the setup size. I consider this solved.
