### ISSUE TITLE
wrong volume in HidHideClient whitelist

### ISSUE THREAD

**Issue by triscan** [ViGEm/HidHide#9]
Hello,
when i add a program from HarddiskVolume2 to the whitelist, HidHideClient add it as HarddiskVolume8.
This happens when my game drive ( Volume8 ) is mounted in a NTFS Folder on Volume2.
In HIdHide Log it Appears correct as Volume2

**Comment by vdubus** [comment]
Is there a way to check if we have this issue?
My brother made the same configuration as me using njz3/vJoy and Joystick Gremlin (in whitelist).
But unlike me, on his side, Joystick Gremlin still can't see the joysticks.

**Comment by triscan** [comment]
Check the Logs.
Windows Event Viewer->Applications and Services -> Nefarius -> Drivers -> HidHide -> Diagnistics
start Joystick Gremlin and Jump to the last few entrys.
you see the full path on HidHideProcessIdCheckFullImageNameAgainstWhitelist
