### ISSUE TITLE
Hihide corrupt/stop working when use DSX (steam)

### ISSUE THREAD

**Issue by stryxz1** [ViGEm/HidHide#95]
got this pop up trying to open after use DSX.

reinstall fixes the problem, but its soon back again
![Screenshot_2](https://user-images.githubusercontent.com/119906902/206262486-a85565c4-980d-4c4b-9b75-416da57635fe.png)

**Comment by nefarius** [comment]
It's not corrupt, this message means some other process, potentially DSX, is currently configuring HH, solve that and it will be good.

**Comment by stryxz1** [comment]
i see, know i just realize that its indeed unistaling hidhide

**Comment by Paliverse** [comment]
In the current Build, DSX has a handle to HidHide the whole time, fixed in v3.

**Comment by nefarius** [comment]
> it might not be the place to ask, but there is plans to make audio jack work on bluetooth?

It is indeed not the place to ask.
