### ISSUE TITLE
volumes [drives] referenced by device index (instead of drive letter) causes problems when indexes change internally

### ISSUE THREAD

**Issue by Hyratel** [ViGEm/HidHide#98]
I lately added a new hard drive for More Games Install Space, and HIDHide stores the whitelist by volume reference (`\Device\HarddiskVolume4`) rather than by drive letter (`D:\`) and somewhere between adding the new drive, and a crash-reboot, the C:\ diskvolume changed from Vol4 to Vol6, and without access to an actual config file or the possibility to textedit the paths directly, I'm stuck with around 20 entries I'm having to rebuild one by one

**Comment by nefarius** [comment]
That's unfortunate but I can't think of any recommendations other than scripting a fix using the CLI.
