### ISSUE TITLE
Where is the file of the list of applications or games that we have added in HH?

### ISSUE THREAD

**Issue by AAide** [ViGEm/HidHide#99]
Where is the file of the list of applications or games that we have added in HH?

If it is saved in the windows registry, is it possible to add the data to be exported and imported directly into the HH software?

**Comment by nefarius** [comment]
It's prohibited for a reason, why would you wanna do that outside the API, use the CLI for these kind of tasks.

**Comment by AAide** [comment]
Because I don't know how to do it on the command line and I would like to do that when I have to reinstall windows, it allows me to just re-import the list of applications that we have already added, and if we have to add all the applications again one by one, it takes a lot of time, so exporting this list and re-importing it saves a lot of time. There is also one thing that poses a problem, it would be nice to have the possibility of sorting the applications added to the list, by name or just filtering on the name of the file, without displaying the entire location of the file .

**Comment by AAide** [comment]
I would like to point out that adding by drag and drop an exe file, which originated in another hard drive because its folder is a symbolic link folder, causes the game not to be detected by the controller, elsewhere have not even happened to add an exe file in the list, which is in symbolic link, you have to go to the source of the exe file to be able to add it in hh

**Comment by nefarius** [comment]
> Because I don't know how to do it on the command line and I would like to do that when I have to reinstall windows, it allows me to just re-import the list of applications that we have already added, and if we have to add all the applications again one by one, it takes a lot of time, so exporting this list and re-importing it saves a lot of time.

Then learn it 😛 it has a help command and everything. Your use case is a job for the CLI.

**Comment by nefarius** [comment]
> I would like to point out that adding by drag and drop an exe file, which originated in another hard drive because its folder is a symbolic link folder, causes the game not to be detected by the controller, elsewhere have not even happened to add an exe file in the list, which is in symbolic link, you have to go to the source of the exe file to be able to add it in hh

Can't tell, you might have found a bug.

**Comment by AAide** [comment]
I am a big user of HH, I associate it with Xpadder to emulate the keyboard keys on a controller to avoid certain problems with games that do not support the controller, or which do not allow you to modify the configuration of the controller, it Uses a lot, it's a must have for me. Thank you for creating this software, it's great.

**Comment by nefarius** [comment]
Great to hear, I consider this solved then 👍
